# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 350)
        Form.setMinimumSize(QtCore.QSize(600, 350))
        Form.setMaximumSize(QtCore.QSize(600, 350))
        Form.setStyleSheet("*{\n"
"    color: rgb(255, 52, 179);\n"
"    color: #FF69B4;\n"
"    font-size: 18px;\n"
"    font-weight: 900;\n"
"    font-family: YouSheBiaoTiYuan;\n"
"}\n"
"QWidget#Form{\n"
"    border-image:url(:/bg/cxk2.png)\n"
"}\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dialog_label = QtWidgets.QLabel(Form)
        self.dialog_label.setStyleSheet("background-color: rgba(245,245,220,0.7);\n"
"font-size: 26px;")
        self.dialog_label.setTextFormat(QtCore.Qt.PlainText)
        self.dialog_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dialog_label.setWordWrap(True)
        self.dialog_label.setObjectName("dialog_label")
        self.verticalLayout.addWidget(self.dialog_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.close_button = QtWidgets.QPushButton(Form)
        self.close_button.setMinimumSize(QtCore.QSize(100, 35))
        self.close_button.setMaximumSize(QtCore.QSize(100, 35))
        self.close_button.setStyleSheet("background-color: rgba(255, 255, 255, 0.6);\n"
"")
        self.close_button.setObjectName("close_button")
        self.horizontalLayout.addWidget(self.close_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dialog_label.setText(_translate("Form", "123"))
        self.close_button.setText(_translate("Form", "确认"))
from qt.qrc import ys_bg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
