# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'midiForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from utils.MoveWidget import MoveWidget


class Ui_midiForm(object):
    def setupUi(self, midiForm):
        midiForm.setObjectName("midiForm")
        midiForm.resize(1024, 512)
        midiForm.setMinimumSize(QtCore.QSize(1024, 512))
        midiForm.setMaximumSize(QtCore.QSize(1024, 512))
        midiForm.setStyleSheet("*{\n"
"    color: rgb(255, 52, 179);\n"
"    color: #FFFFFF;\n"
"    font-size: 25px;\n"
"    font-weight: 900;\n"
"    font-family: YouSheBiaoTiYuan;\n"
"}\n"
"QLabel,QRadioButton{\n"
"    background-color: transparent;\n"
"}\n"
"QListWidget::item::selected:active\n"
"{ \n"
"    background-color: rgba(255, 20, 147, 0.7);\n"
"    border-width:0;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(midiForm)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bg_widget = QtWidgets.QWidget(midiForm)
        self.bg_widget.setStyleSheet("QWidget#bg_widget{\n"
"    border-image:url(:/bg/cxk.png);\n"
"}")
        self.bg_widget.setObjectName("bg_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.bg_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.bg_widget)
        self.widget_2.setStyleSheet("#widget_2{\n"
"    background-color: rgba(0, 178, 238, 0.5);\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(18, 18, 18, 18)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dir_label = QtWidgets.QLabel(self.widget_2)
        self.dir_label.setMinimumSize(QtCore.QSize(0, 25))
        self.dir_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.dir_label.setStyleSheet("")
        self.dir_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dir_label.setObjectName("dir_label")
        self.verticalLayout.addWidget(self.dir_label)
        self.midiSelect_listWidget = QtWidgets.QListWidget(self.widget_2)
        self.midiSelect_listWidget.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);\n"
"")
        self.midiSelect_listWidget.setObjectName("midiSelect_listWidget")
        self.verticalLayout.addWidget(self.midiSelect_listWidget)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mid_label = QtWidgets.QLabel(self.widget_2)
        self.mid_label.setMinimumSize(QtCore.QSize(490, 50))
        self.mid_label.setMaximumSize(QtCore.QSize(490, 50))
        self.mid_label.setStyleSheet("color: rgb(255,20,147);")
        self.mid_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mid_label.setObjectName("mid_label")
        self.horizontalLayout_2.addWidget(self.mid_label)
        self.close_pushButton = QtWidgets.QPushButton(self.widget_2)
        self.close_pushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.close_pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.close_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0.3);\n"
"    image: url(:/icon/static/icon/close.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 0.6);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"}")
        self.close_pushButton.setText("")
        self.close_pushButton.setFlat(False)
        self.close_pushButton.setObjectName("close_pushButton")
        self.horizontalLayout_2.addWidget(self.close_pushButton)
        self.horizontalLayout_2.setStretch(0, 9)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tip_label = QtWidgets.QLabel(self.widget_2)
        self.tip_label.setMinimumSize(QtCore.QSize(0, 60))
        self.tip_label.setMaximumSize(QtCore.QSize(16777215, 60))
        self.tip_label.setStyleSheet("")
        self.tip_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tip_label.setWordWrap(False)
        self.tip_label.setObjectName("tip_label")
        self.horizontalLayout_7.addWidget(self.tip_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.horizontalLayout_7.setStretch(0, 9)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.mode1_radioButton = QtWidgets.QRadioButton(self.widget_2)
        self.mode1_radioButton.setChecked(True)
        self.mode1_radioButton.setObjectName("mode1_radioButton")
        self.horizontalLayout_3.addWidget(self.mode1_radioButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.mode2_radioButton = QtWidgets.QRadioButton(self.widget_2)
        self.mode2_radioButton.setObjectName("mode2_radioButton")
        self.horizontalLayout_3.addWidget(self.mode2_radioButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.speed_label = QtWidgets.QLabel(self.widget_2)
        self.speed_label.setMinimumSize(QtCore.QSize(280, 40))
        self.speed_label.setMaximumSize(QtCore.QSize(280, 40))
        self.speed_label.setStyleSheet("")
        self.speed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_label.setObjectName("speed_label")
        self.horizontalLayout_5.addWidget(self.speed_label)
        self.speed_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.speed_doubleSpinBox.setMinimumSize(QtCore.QSize(100, 40))
        self.speed_doubleSpinBox.setMaximumSize(QtCore.QSize(100, 40))
        self.speed_doubleSpinBox.setStyleSheet("QDoubleSpinBox{\n"
"    background-color: rgba(255,255,255,0.3);\n"
"}\n"
"QDoubleSpinBox:up-button \n"
"{\n"
"    subcontrol-origin:border;\n"
"    subcontrol-position:right;\n"
"    image: url(:/icon/static/icon/add.png);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    background-color: rgba(255,255,255,0.5);\n"
"}\n"
"\n"
"QDoubleSpinBox:down-button \n"
"{\n"
"    subcontrol-origin:border;\n"
"    subcontrol-position:left;\n"
"    image: url(:/icon/static/icon/move.png);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    background-color: rgba(255,255,255,0.5);\n"
"}\n"
"QDoubleSpinBox:up-button:hover{\n"
"    background-color: rgba(255,255,255,0.7);\n"
"}\n"
"QDoubleSpinBox:up-button:pressed{\n"
"    background-color: rgba(255,255,255,0.1);\n"
"}")
        self.speed_doubleSpinBox.setDecimals(1)
        self.speed_doubleSpinBox.setMinimum(0.5)
        self.speed_doubleSpinBox.setMaximum(5.0)
        self.speed_doubleSpinBox.setSingleStep(0.1)
        self.speed_doubleSpinBox.setProperty("value", 1.0)
        self.speed_doubleSpinBox.setObjectName("speed_doubleSpinBox")
        self.horizontalLayout_5.addWidget(self.speed_doubleSpinBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.wait_label = QtWidgets.QLabel(self.widget_2)
        self.wait_label.setMinimumSize(QtCore.QSize(280, 40))
        self.wait_label.setMaximumSize(QtCore.QSize(280, 40))
        self.wait_label.setStyleSheet("")
        self.wait_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wait_label.setObjectName("wait_label")
        self.horizontalLayout_4.addWidget(self.wait_label)
        self.wait_spinBox = QtWidgets.QSpinBox(self.widget_2)
        self.wait_spinBox.setMinimumSize(QtCore.QSize(100, 40))
        self.wait_spinBox.setMaximumSize(QtCore.QSize(100, 40))
        self.wait_spinBox.setStyleSheet("QSpinBox{\n"
"    background-color: rgba(255,255,255,0.3);\n"
"}\n"
"QSpinBox:up-button \n"
"{\n"
"    subcontrol-origin:border;\n"
"    subcontrol-position:right;\n"
"    image: url(:/icon/static/icon/add.png);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    background-color: rgba(255,255,255,0.5);\n"
"}\n"
"\n"
"QSpinBox:down-button \n"
"{\n"
"    subcontrol-origin:border;\n"
"    subcontrol-position:left;\n"
"    image: url(:/icon/static/icon/move.png);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    background-color: rgba(255,255,255,0.5);\n"
"}\n"
"QSpinBox:up-button:hover{\n"
"    background-color: rgba(255,255,255,0.7);\n"
"}\n"
"QSpinBox:up-button:pressed{\n"
"    background-color: rgba(255,255,255,0.1);\n"
"}\n"
"QSpinBox:down-button:hover{\n"
"    background-color: rgba(255,255,255,0.7);\n"
"}\n"
"QSpinBox:down-button:pressed{\n"
"    background-color: rgba(255,255,255,0.1);\n"
"}")
        self.wait_spinBox.setKeyboardTracking(True)
        self.wait_spinBox.setMinimum(5)
        self.wait_spinBox.setMaximum(20)
        self.wait_spinBox.setSingleStep(5)
        self.wait_spinBox.setObjectName("wait_spinBox")
        self.horizontalLayout_4.addWidget(self.wait_spinBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.progress_label = QtWidgets.QLabel(self.widget_2)
        self.progress_label.setMinimumSize(QtCore.QSize(100, 35))
        self.progress_label.setMaximumSize(QtCore.QSize(100, 35))
        self.progress_label.setStyleSheet("")
        self.progress_label.setAlignment(QtCore.Qt.AlignCenter)
        self.progress_label.setObjectName("progress_label")
        self.horizontalLayout_6.addWidget(self.progress_label)
        self.progressBar = QtWidgets.QProgressBar(self.widget_2)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    border: 2px solid white;\n"
"    background-color: #E0E0E0;\n"
"    min-height: 8px;\n"
"    max-height: 8px;\n"
"    border-radius: 3px;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #BF3EFF;\n"
"    width: 7px;\n"
"}\n"
"")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_6.addWidget(self.progressBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.play_pushButton = QtWidgets.QPushButton(self.widget_2)
        self.play_pushButton.setMinimumSize(QtCore.QSize(110, 40))
        self.play_pushButton.setMaximumSize(QtCore.QSize(110, 40))
        self.play_pushButton.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);\n"
"")
        self.play_pushButton.setObjectName("play_pushButton")
        self.horizontalLayout_9.addWidget(self.play_pushButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.stop_pushButton = QtWidgets.QPushButton(self.widget_2)
        self.stop_pushButton.setMinimumSize(QtCore.QSize(110, 40))
        self.stop_pushButton.setMaximumSize(QtCore.QSize(110, 40))
        self.stop_pushButton.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);\n"
"")
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.horizontalLayout_9.addWidget(self.stop_pushButton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(2, 2)
        self.horizontalLayout_9.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.bg_widget)
        self.speed_label.setBuddy(self.wait_spinBox)
        self.wait_label.setBuddy(self.wait_spinBox)

        self.retranslateUi(midiForm)
        QtCore.QMetaObject.connectSlotsByName(midiForm)

    def retranslateUi(self, midiForm):
        _translate = QtCore.QCoreApplication.translate
        midiForm.setWindowTitle(_translate("midiForm", "Form"))
        self.dir_label.setText(_translate("midiForm", "midi预选目录，请选择要演奏的midi"))
        self.mid_label.setText(_translate("midiForm", "当前未选择midi，请选择后点击开始"))
        self.tip_label.setText(_translate("midiForm", "当模式一无法正常演奏时，请切换模式二，\n"
"反之同理"))
        self.mode1_radioButton.setText(_translate("midiForm", "模式1"))
        self.mode2_radioButton.setText(_translate("midiForm", "模式2"))
        self.speed_label.setText(_translate("midiForm", "演奏速度(倍)"))
        self.wait_label.setText(_translate("midiForm", "等待间隔(&s)"))
        self.progress_label.setText(_translate("midiForm", "演奏进度"))
        self.play_pushButton.setText(_translate("midiForm", "开始"))
        self.stop_pushButton.setText(_translate("midiForm", "停止"))
from qt.qrc import ys_bg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # midiForm = QtWidgets.QWidget()
    midiForm = MoveWidget()
    ui = Ui_midiForm()
    ui.setupUi(midiForm)
    midiForm.show()
    sys.exit(app.exec_())
