# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScriptForm(object):
    def setupUi(self, ScriptForm):
        ScriptForm.setObjectName("ScriptForm")
        ScriptForm.resize(768, 593)
        ScriptForm.setStyleSheet("QWidget#ScriptForm{\n"
"    border-image: url(:/bg/music-instruments-2887457.jpg);\n"
"}\n"
"")
        self.widget = QtWidgets.QWidget(ScriptForm)
        self.widget.setGeometry(QtCore.QRect(260, 120, 281, 251))
        self.widget.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 261, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mid_label1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.mid_label1.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.mid_label1.setObjectName("mid_label1")
        self.verticalLayout.addWidget(self.mid_label1)
        self.mid_label1_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.mid_label1_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.mid_label1_2.setObjectName("mid_label1_2")
        self.verticalLayout.addWidget(self.mid_label1_2)
        self.mid_label1_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.mid_label1_3.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.mid_label1_3.setObjectName("mid_label1_3")
        self.verticalLayout.addWidget(self.mid_label1_3)

        self.retranslateUi(ScriptForm)
        # self.mid_label1_2.linkHovered['QString'].connect(ScriptForm.hover1)
        self.mid_label1_2.linkHovered['QString'].connect(lambda : print(0))
        QtCore.QMetaObject.connectSlotsByName(ScriptForm)

    def retranslateUi(self, ScriptForm):
        _translate = QtCore.QCoreApplication.translate
        ScriptForm.setWindowTitle(_translate("ScriptForm", "Form"))
        self.mid_label1.setText(_translate("ScriptForm", "样式1"))
        self.mid_label1_2.setText(_translate("ScriptForm", "样式1"))
        self.mid_label1_3.setText(_translate("ScriptForm", "样式1"))
from qt.qrc import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ScriptForm = QtWidgets.QWidget()

    ScriptForm.hover1 = lambda: print('0')

    ui = Ui_ScriptForm()
    ui.setupUi(ScriptForm)
    ScriptForm.show()
    sys.exit(app.exec_())
